PACKAGE_NAME="amdxdna"
PACKAGE_VERSION="2.25.0.r20260723.g1e1276c"
BUILD_EXCLUSIVE_KERNEL_MIN="6.10"

PRE_BUILD="./configure_kernel.sh"
MAKE[0]="make -C driver/amdxdna KERNEL_SRC=${kernel_source_dir} KERNEL_VER=${kernelver} XDNA_DRIVER_VERSION=2.25.0 XDNA_HASH=1e1276c96e4cbf6ad2154acb5e1a42cdbb2f75a1"
CLEAN="make -C driver/amdxdna clean KERNEL_SRC=${kernel_source_dir}"

BUILT_MODULE_NAME[0]="amdxdna"
BUILT_MODULE_LOCATION[0]="driver/amdxdna/build/driver/amdxdna"
DEST_MODULE_LOCATION[0]="/kernel/extras"

AUTOINSTALL="yes"
