# Modified for amdtop native theme schema 1 in 2026.
# Source: https://github.com/aristocratos/btop/blob/v1.4.7/themes/everforest-dark-medium.theme
# btop source commit: 6e39144aaf5a6bc01b9f795010b0914431067183

schema = 1
name = "everforest-dark-medium"

[ui]
background = "#2d353b"
foreground = "#d3c6aa"
title = "#d3c6aa"
highlight = "#e67e80"
selected_background = "#3d484d"
selected_foreground = "#dbbc7f"
inactive = "#2d353b"
graph_text = "#d3c6aa"
misc = "#a7c080"

[stats]
clock = "#a7c080"
power = "#d3c6aa"
fan = "#d3c6aa"
bandwidth = "#d3c6aa"

[borders]
cpu = "#3d484d"
gpu = "#3d484d"
memory = "#3d484d"
npu = "#3d484d"
processes = "#3d484d"

[gradients.temperature]
stops = [
  { at = 0.0, color = "#a7c080" },
  { at = 0.5, color = "#dbbc7f" },
  { at = 1.0, color = "#f85552" },
]

[gradients.cpu]
stops = [
  { at = 0.0, color = "#a7c080" },
  { at = 0.5, color = "#dbbc7f" },
  { at = 1.0, color = "#f85552" },
]

[gradients.gpu]
stops = [
  { at = 0.0, color = "#a7c080" },
  { at = 0.5, color = "#dbbc7f" },
  { at = 1.0, color = "#f85552" },
]

[gradients.memory]
stops = [
  { at = 0.0, color = "#a7c080" },
  { at = 0.5, color = "#dbbc7f" },
  { at = 1.0, color = "#f85552" },
]

[gradients.npu]
stops = [
  { at = 0.0, color = "#a7c080" },
  { at = 0.5, color = "#e67e80" },
  { at = 1.0, color = "#f85552" },
]

[gradients.process]
stops = [
  { at = 0.0, color = "#a7c080" },
  { at = 0.5, color = "#e67e80" },
  { at = 1.0, color = "#f85552" },
]
